22-django/ProyectoDjango/ProyectoDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('', include('pages.urls')),
    path('', include('blog.urls')),
]

# Ruta imagenes
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

22-django/ProyectoDjango/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('articulos/', views.list, name='list_articles'),
    path('categoria/<int:category_id>/', views.category, name='category'),
    path('articulo/<int:article_id>/', views.article, name='article'),
]

22-django/ProyectoDjango/mainapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('inicio/', views.index, name="inicio"),
    path('resgistro/', views.register_page, name="register"),
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),
]

22-django/ProyectoDjango/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pagina/<str:slug>', views.page, name="page"),
]

22-django/ProyectoDjango/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nombre de la categoría")
    description = models.CharField(max_length=255, verbose_name="Descripción")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    class Meta:
        verbose_name = "Categoría"
        verbose_name_plural = "Categorías"

    def __str__(self):
        return self.name  # Muestra el nombre de la categoría en el panel admin


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    content = RichTextField(verbose_name="Contenido")
    image = models.ImageField(default='null', verbose_name="Imagen", upload_to="articles")
    public = models.BooleanField(verbose_name="¿Publicado?")
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False, verbose_name="Usuario")
    categories = models.ManyToManyField(Category, verbose_name="Categorías", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    class Meta:
        verbose_name = "Artículo"
        verbose_name_plural = "Artículos"
        ordering = ['-created_at']

    def __str__(self):
        return self.title  # Muestra el título del artículo en el panel admin

22-django/ProyectoDjango/mainapp/models.py
from django.db import models

# Create your models here.

22-django/ProyectoDjango/pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=50, verbose_name="Título")
    content = RichTextField(verbose_name="Contenido")
    slug = models.CharField(unique=True, max_length=150, verbose_name="URL Amigable")
    order = models.IntegerField(default=0, verbose_name="Orden")
    visible = models.BooleanField(default=True, verbose_name="¿Visible?")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    class Meta:
        verbose_name = "Página"
        verbose_name_plural = "Páginas"

    def __str__(self):
        return self.title # Muestra el título de la página en el panel admin

22-django/ProyectoDjango/mainapp/forms.py
from django import forms
from django.core import validators


from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]

22-django/ProyectoDjango/blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Category, Article
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login/')
def list(request):
    #sacar todos los articulos
    articles = Article.objects.all()
    # Paginar los articulos
    paginator = Paginator(articles, 2)
    #recoger el numero de pagina
    page = request.GET.get('page')
    page_articles = paginator.get_page(page)

    return render(request, 'articles/list.html', {
        'title': 'Artículos',
        'articles': page_articles
    })

@login_required(login_url='/login/')
def category(request, category_id):

    category = get_object_or_404(Category, id=category_id)
    articles = Article.objects.filter(categories=category_id)

    return render(request, 'categories/category.html', {
        'category': category,
        'articles': articles
    })

@login_required(login_url='/login/')
def article(request, article_id):

    article = get_object_or_404(Article, id=article_id)

    return render(request, 'articles/detail.html', {
        'article': article
    })

22-django/ProyectoDjango/mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from mainapp.forms import RegisterForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(request):
    return render(request, "mainapp/index.html", {
        'title': 'Inicio'
        })

def about(request):
    return render(request, "mainapp/about.html", {
        'title': 'Sobre Nosotros'
        })

def register_page(request):

    if request.user.is_authenticated:
        return redirect('index')
    else:
        register_form = RegisterForm()

        if request.method == 'POST':
            register_form = RegisterForm(request.POST)
            if register_form.is_valid():
                register_form.save()
                messages.success(request, 'Usuario registrado correctamente')

                return index(request)

        return render(request, "mainapp/users/register.html", {
            'title': 'Registro de Usuario',
            'register_form': register_form
            })


def login_page(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                messages.warning(request, 'Usuario o contraseña incorrecta')

        return render(request, "mainapp/users/login.html", {
            'title': 'Iniciar Sesión'
            })

def logout_user(request):
    logout(request)

    return redirect('login')

22-django/ProyectoDjango/pages/views.py
from django.shortcuts import render
from .models import Page
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login/')
def page(request, slug):

    page = Page.objects.get(slug = slug)


    return render(request, 'pages/page.html', {
        "page": page,
    })

22-django/ProyectoDjango/blog/templates/articles/articles.html
{% for article in articles %}

    <article class="article-item">

        {% if article.image != 'null' and article.image.url|length >= 1 %}
            <div class="image" >
                <img src="{{ article.image.url }}" alt="Imagen del artículo {{ article.title }}">
            </div>
        {% endif %}

        <div class="data">
            <h2 class="title">
                <a href="{% url 'article' article.id %}">{{ article.title }}</a>
            </h2>
            <p>
                {% for category in article.categories.all %}
                    <a href="" >{{ category}}</a>
                    {% if forloop.counter < article.categories.all|length %}
                        {{"--"}}
                    {% endif %}

                {% endfor %}
            </p>
            <span class="date">
                {{article.user.username}} {{article.user.last_name}}
                |
                {{ article.created_at }}
            </span>
            <p >
                {{ article.content|safe}}
            </p>
        </div>
    </article>
{% endfor %}

22-django/ProyectoDjango/blog/templates/articles/detail.html
{% extends "layouts/layout.html" %}
{% block title %} {{article.title}} {% endblock %}

{% block content %}

    {% if article.image != 'null' and article.image.url|length >= 1 %}
        <div class="image" >
            <img src="{{ article.image.url }}" alt="Imagen del artículo {{ article.title }}">
        </div>
    {% endif %}

<h1 class="title">{{article.title}}</h1>
<span class="date">Publicado el {{article.created_at}}</span>
<p class="content">{{article.content|safe}}</p>

{% endblock %}

22-django/ProyectoDjango/blog/templates/articles/list.html
{% extends "layouts/layout.html" %}
{% block title %} {{title}} {% endblock %}

{% block content %}

    <h1 class="title">{{title}}</h1>

    {% include 'articles/articles.html' %}

    {% include 'articles/pagination.html' %}

{% endblock %}

22-django/ProyectoDjango/blog/templates/articles/pagination.html
<div class="pagination">
    {% if articles.has_previous %}
        <a href="?page=1">&laquo; Primero</a>
        <a href="?page={{ articles.previous_page_number }}">&lt; Anterior</a>
    {% endif %}

    <span class="actual">
        Página {{ articles.number }} de {{ articles.paginator.num_pages }}
    </span>

    {% if articles.has_next %}
        <a href="?page={{ articles.next_page_number }}">Siguiente &gt;</a>
        <a href="?page={{ articles.paginator.num_pages }}">Último &raquo;</a>
    {% endif %}
    

</div>

22-django/ProyectoDjango/blog/templates/categories/category.html
{% extends "layouts/layout.html" %}
{% block title %} {{category.name}} {% endblock %}

{% block content %}

    <h1 class="title">{{category.name}}</h1>
    <p>{{category.description}}</p>


    {% include 'articles/articles.html' with articles=category.article_set.all %}

{% endblock %}

22-django/ProyectoDjango/mainapp/templates/layouts/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Título de cada pagina con bloques -->
    <title>
        {% block title %}
        {% endblock %}
        | Manuel Ríos
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
    <body>
        <!--Cabecera de la página-->
        <header>
            <div id="logotipo">
                <!--Logo Django-->
                <img src="{% static 'images/logo.png' %}" alt="Logotipo">
                <h1>Proyecto con Django</h1>
            </div>
        </header>
        <nav id="menu">
            <ul>
                <li><a href="{% url 'index' %}">Inicio</a></li>
                {% if user.email %}
                    <li>
                        <a href="{% url 'list_articles' %}">Categorias</a>
                        <ul>
                            {% for category in categories %}
                                <li>
                                    <a href="{% url 'category' category.0 %}">{{ category.1 }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% for page in pages %}
                    <li><a href="{% url 'page' page.2 %}">{{ page.1 }}</a></li>
                    {% endfor %}
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'register' %}">Registro</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}

            </ul>
        </nav>
        <div class="barra">
            <span class="esquina-izquierda"></span>
            <span class="relleno-barra"></span>
            <span class="esquina-derecha"></span>
        </div>

        <div id="content">
            <div class="box">
                {% block content %}
                    <!--Código que viene de templates-->
                    <strong>Contenido del bloque original</strong>
                {% endblock %}
            </div>
        </div>
        <footer>
            <p>Master en Python</p>
            <p>Desarrollado por ManRio &copy; - {% now "Y" %} </p>
        </footer>
    </body>
</html>

22-django/ProyectoDjango/mainapp/templates/mainapp/about.html
{% extends "layouts/layout.html" %}
{% block title %} {{title}} {% endblock %}

{% block content %}

<h1>{{title}}</h1>

{% endblock %}

22-django/ProyectoDjango/mainapp/templates/mainapp/index.html
{% extends "layouts/layout.html" %}
{% block title %} {{title}} {% endblock %}

{% block content %}

<h1>{{title}}</h1>

<p>Bienvenidos a nuestro sitio web desarrollado con Django. Aquí encontrarás información relevante sobre nuestro proyecto y el equipo detrás de él.</p>
<hr/>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-succes">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% if user.email %}
    <h2> Bienvenido {{ request.user.first_name }} {{ user.last_name }} </h2>
    <p>
        {{ user.email}}
    </p>
    {% else %}
    <h2> Identificate para ver más cosas </h2>
    {% endif %}

{% endblock %}

22-django/ProyectoDjango/mainapp/templates/mainapp/users/login.html
{% extends "layouts/layout.html" %}
{% block title %} {{title}} {% endblock %}

{% block content %}

<h1>{{title}}</h1>

{% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

{{ register_form.errors }}

<form method="POST" action="">
    {% csrf_token %}

    <label for="username">Nombre de usuario</label>
    <input type="text" name="username" placeholder="Pepito_Pepe"></input>

    <label for="password">Contraseña</label>
    <input type="password" name="password" placeholder="Recuerda que tu contraseña es privada pequeño padawan"></input>


    <input type="submit" value="Login"></input>
</form>

{% endblock %}

22-django/ProyectoDjango/mainapp/templates/mainapp/users/register.html
{% extends "layouts/layout.html" %}
{% block title %} {{title}} {% endblock %}

{% block content %}

<h1>{{title}}</h1>

{{ register_form.errors }}

<form method="POST" action="">
    {% csrf_token %}

    {% comment "" %}
    {{ register_form.as_p }}
    {% endcomment %}

    {% for field in register_form %}
        <label>{{field.label}}</label>
        {{field}}
    {% endfor %}

    <input type="submit" value="Registrarse"></input>
</form>

{% endblock %}

22-django/ProyectoDjango/pages/templates/pages/page.html
{% extends "layouts/layout.html" %}
{% block title %} {{page.title}} {% endblock %}

{% block content %}

<h1 class="title">{{page.title}}</h1>
<span class="date">Publicado el {{page.created_at}}</span>
<p class="content">{{page.content|safe}}</p>

{% endblock %}